### ISSUE TITLE
Compilation instructions clarity

### ISSUE THREAD

**Issue by pritamdodeja** [MyLab-odyssey/ED_BMSdiag#14]
In the instructions at https://github.com/MyLab-odyssey/ED_BMSdiag/wiki/Installation where you say to download and unzip, the instructions could be made clearer.  Specifically after the sketch is opened, the dependent libraries which you have already included in the repository need to be loaded individually through the ide.  After I did this, I was able to compile and flash the sketch.  I am still waiting for the shield so can't make any further progress :(

**Comment by MyLab-odyssey** [comment]
This is normally not necessary, so please explain used OS, used Arduino IDE version and the steps you did! When there is an "Arduino" folder within your "Documents" section and the nested folders for the "libraries" and the "ED_BMSdiag" sketch are present the IDE will get the dependencies by it's own. 

**Read carefully: "...then copy the files to your Arduino folder."** - You have to run the Arduino IDE one time after installation to let the IDE create the "Arduino"-folder, then place the unziped content into that folder as explained. A more detailed installation instruction is already [here](https://github.com/MyLab-odyssey/ED_BMSdiag/wiki/Installation).

The tool is already out for more than a year and no other user complained. So please verify your taken steps and report. I will close development of the project in one week...
