### ISSUE TITLE
Does this also work with current Mercedes EQ models

### ISSUE THREAD

**Issue by SamuelBrucksch** [MyLab-odyssey/ED_BMSdiag#31]
Hi,

do you happen to know, if this project also works with newer EQ models of Mercedes? Like EQ A/B/C/V? Or do you maybe know other projects that somehow get data from those models?

Cheers
Samuel

**Comment by MyLab-odyssey** [comment]
Hi Samuel,

**please don't use the tools** (ED_BMSdiag and ED4scan on new Mercedes EQs! I assume it will not work, as they have nothing in common. The current Smart EQs are based on Renault SW and HW (despite some queries for the BMS) and have no real 'Daimler heritage'.

Best regards
odyssey
