### ISSUE TITLE
ERROR when INT pin differs from pin 2

### ISSUE THREAD

**Issue by nighteagle1974** [MyLab-odyssey/ED_BMSdiag#34]
Have build together Tool - all is working - Can-Bus Cable still also work but some functions not working like BMS and ofter F#1

Car is ED3 from 2014

Here:

-----------------------------------------
--- ED Battery Management Diagnostics ---
--- v1.0.5                            ---
-----------------------------------------

Connect to OBD port - Waiting for CAN-Bus 
.CONNECTED
-----------------------------------------
NLG6 detected
-----------------------------------------
........Reading data.........F#1
* Measurement failed *
Reading data.F#1
* Measurement failed *
Reading data.OK
-----------------------------------------
Status Cooling- and Subsystems: 
Temperature   : 7.6 degC
Cooling fan   : 0.0 %
Cooling pump  : 68.6 %, 9 degC
              : 13.5 V, 1.8 A
OTR:
Cooling fan   : 7 h
Cooling pump  : 4194 h
Battery heater: 52 h, OFF
Vaccum pump   : 79.391 h
Pressure 1, 2 : -604 mbar, -607 mbar
-----------------------------------------

-----------------------------------------
Battery VIN: WME45139014513901
Time [hh:mm]: 00:00,   ODO : 0 km
-----------------------------------------
SOC : 82.5 %, realSOC: 0.0 %
HV  : 0.0 V, 0.00 A, 0.00 kW
LV  : 0.0 V
-----------------------------------------
ENTER command... (? for help)
CMD >>

New Start of Tool  - how can i get back from submenue?

-----------------------------------------
--- ED Battery Management Diagnostics ---
--- v1.0.5                            ---
-----------------------------------------

Connect to OBD port - Waiting for CAN-Bus 
.CONNECTED
-----------------------------------------
NLG6 detected
-----------------------------------------
........Reading data.........F#1
* Measurement failed *
Reading data.F#1
* Measurement failed *
Reading data.OK
-----------------------------------------
Status Cooling- and Subsystems: 
Temperature   : 8.3 degC
Cooling fan   : 0.0 %
Cooling pump  : 68.6 %, 11 degC
              : 14.1 V, 1.8 A
OTR:
Cooling fan   : 7 h
Cooling pump  : 4194 h
Battery heater: 52 h, OFF
Vaccum pump   : 79.391 h
Pressure 1, 2 : -604 mbar, -607 mbar
-----------------------------------------

-----------------------------------------
Battery VIN: WME45139014513901
Time [hh:mm]: 00:00,   ODO : 0 km
-----------------------------------------
SOC : 82.5 %, realSOC: 0.0 %
HV  : 0.0 V, 0.00 A, 0.00 kW
LV  : 0.0 V
-----------------------------------------
ENTER command... (? for help)
CMD >>

CMD >>nlg6
NLG6 >>?
* NLG6 Menu:
  all   Get complete dataset
  v     Get voltages, amps & status
  t     Get temperatures
NLG6 >>v
.F#1NLG6 >>all
Reading data.F#1
* Measurement failed *
NLG6 >>v
.F#1NLG6 >>t
Temperatures Charger-Unit /degC: 
Reported       : 9
Cooling plate  : 9
Inlet socket   : 9
Internal values: 
9, 9, 8, 9, 8, 9, 8, 9
NLG6 >>all
Reading data.F#1
* Measurement failed *
NLG6 >>`

**Comment by nighteagle1974** [comment]
Have also test the V1.0.8:


-----------------------------------------
--- ED Battery Management Diagnostics ---
--- v1.0.8b (451)                     ---
-----------------------------------------

Connect to OBD port - Waiting for CAN-Bus 
.CONNECTED
-----------------------------------------
NLG6 detected
-----------------------------------------
........Reading data.........F#1
* Measurement failed *
Reading data.F#1
* Measurement failed *
Reading data.OK
-----------------------------------------
Status Cooling- and Subsystems: 
Temperature   : 7.6 degC
Cooling fan   : 0.0 %
Cooling pump  : 69.0 %, 10 degC
              : 14.1 V, 1.8 A
OTR:
Cooling fan   : 7 h
Cooling pump  : 4194 h
Battery heater: 52 h, OFF
Vaccum pump   : 79.392 h
Pressure 1, 2 : -603 mbar, -606 mbar
-----------------------------------------


-----------------------------------------
Battery VIN: WME45139014513901
Time [hh:mm]: 00:00,   ODO : 0 km
-----------------------------------------
SOC : 82.5 %, realSOC: 0.0 %
HV  : 0.0 V, 0.00 A, 0.00 kW
LV  : 0.0 V
CAUTION: Low voltage battery very low [< 12.0 V]. Check with an actual meter.
RECHECK after car off for >60 mins
Car off for: 0.0 minutes
-----------------------------------------
ENTER command... (? for help)
CMD >>bms
BMS >>all
Reading data.........F#1
* Measurement failed *
BMS >>?
* BMS Menu:
  all   Get complete dataset
  v     Get voltages
  t     Get temperatures
BMS >>v
CV mean : 3987 mV, dV = 22 mV
CV min  : 3975 mV
CV max  : 3997 mV
OCVtimer: 0 s
BMS >>t
Temperatures Battery-Unit /degC: 
module 1: 10.6, 9.6, 10.0
module 2: 9.5, 22.2, 412.0
module 3: -500.0, 0.0, 0.0
   mean : 10.0, min : 9.6, max : 10.6
coolant : 9.5
BMS >>..
CMD >>?
* Main Menu:
  BMS          Submenu
  CS           Submenu
  NLG6         Submenu
  all          Run all tests
  rpt          Show battery report

  help         List commands
  info         Show logging state
  log          Logging
               [on/off] or [on/off] [time/s]
  reset        Reset to factory defaults (initial dump, logging off)
  initial      Configure initial dump on or off
               [on/off]
  experimental Configure whether to include experimental data
               [on/off]

  #     Show real time data
CMD >>nlg6
NLG6 >>?
* NLG6 Menu:
  all   Get complete dataset
  v     Get voltages, amps & status
  t     Get temperatures
NLG6 >>all
Reading data.F#1
* Measurement failed *
NLG6 >>v
.F#1NLG6 >>t
Temperatures Charger-Unit /degC: 
Reported       : 9
Cooling plate  : 8
Inlet socket   : 9
Internal values: 
9, 9, 8, 9, 8, 9, 8, 9
NLG6 >>.
CMD: not recognized
NLG6 >>..
CMD >>?
* Main Menu:
  BMS          Submenu
  CS           Submenu
  NLG6         Submenu
  all          Run all tests
  rpt          Show battery report

  help         List commands
  info         Show logging state
  log          Logging
               [on/off] or [on/off] [time/s]
  reset        Reset to factory defaults (initial dump, logging off)
  initial      Configure initial dump on or off
               [on/off]
  experimental Configure whether to include experimental data
               [on/off]

  #     Show real time data
CMD >>cs
CS >>?
* CS Menu:
  all   Get complete dataset
CS >>all
Reading data.OK
-----------------------------------------
Status Cooling- and Subsystems: 
Temperature   : 7.8 degC
Cooling fan   : 0.0 %
Cooling pump  : 69.0 %, 10 degC
              : 14.1 V, 1.8 A
OTR:
Cooling fan   : 7 h
Cooling pump  : 4194 h
Battery heater: 52 h, OFF
Vaccum pump   : 79.392 h
Pressure 1, 2 : -603 mbar, -606 mbar
-----------------------------------------
CS >>..
CMD >>?
* Main Menu:
  BMS          Submenu
  CS           Submenu
  NLG6         Submenu
  all          Run all tests
  rpt          Show battery report

  help         List commands
  info         Show logging state
  log          Logging
               [on/off] or [on/off] [time/s]
  reset        Reset to factory defaults (initial dump, logging off)
  initial      Configure initial dump on or off
               [on/off]
  experimental Configure whether to include experimental data
               [on/off]

  #     Show real time data
CMD >>all
Reading data.........F#1
* Measurement failed *
Reading data.F#1
* Measurement failed *
Reading data.OK
-----------------------------------------
Status Cooling- and Subsystems: 
Temperature   : 7.8 degC
Cooling fan   : 0.0 %
Cooling pump  : 69.0 %, 10 degC
              : 14.1 V, 1.8 A
OTR:
Cooling fan   : 7 h
Cooling pump  : 4194 h
Battery heater: 52 h, OFF
Vaccum pump   : 79.392 h
Pressure 1, 2 : -603 mbar, -606 mbar
-----------------------------------------
CMD >>rpt
Reading data.........F#1
* Measurement failed *
CMD >>ino
CMD: not recognized
CMD >>info
Battery VIN: WME45139014513901
NLG6: 1
Logging interval: 30 s
Logging is OFF
Initial dump is ON
Experimental data is OFF
CMD >>?
* Main Menu:
  BMS          Submenu
  CS           Submenu
  NLG6         Submenu
  all          Run all tests
  rpt          Show battery report

  help         List commands
  info         Show logging state
  log          Logging
               [on/off] or [on/off] [time/s]
  reset        Reset to factory defaults (initial dump, logging off)
  initial      Configure initial dump on or off
               [on/off]
  experimental Configure whether to include experimental data
               [on/off]

  #     Show real time data
CMD >>experimental
CMD >>all
Reading data.........F#1
* Measurement failed *
Reading data.F#1
* Measurement failed *
Reading data.OK
-----------------------------------------
Status Cooling- and Subsystems: 
Temperature   : 7.8 degC
Cooling fan   : 0.0 %
Cooling pump  : 69.0 %, 10 degC
              : 14.1 V, 1.8 A
OTR:
Cooling fan   : 7 h
Cooling pump  : 4194 h
Battery heater: 52 h, OFF
Vaccum pump   : 79.392 h
Pressure 1, 2 : -603 mbar, -606 mbar
-----------------------------------------
CMD >>bms
BMS >>all
Reading data.........F#1
* Measurement failed *
BMS >>

**Comment by nighteagle1974** [comment]
**Problem solved!!!!**

I use the cheaper keyestudio CAN-Shield for the Arduino UNO.
And if you read the connection-overview you see the Pin8 is INT instead of the Sparkfun-Can-Shield it uses PIN2.
So i have replace all 8 places the

**digitalRead(2)** 

with 

**digitalRead(8)**

Now it works.

I think is better to make Pin-Definitions on the beginning of the Sources - so everybody can change it one time - and make some comments for different boards. I will check if i can do this.

My decision was the keyestudio board costs around 9 €  on ebay and the Sparkfun 37 €.

**So the next is to have the new version installed i found 1.0.8 here:
https://github.com/jim-sokoloff/ED_BMSdiag/releases/tag/v1.0.8**

**Comment by MyLab-odyssey** [comment]
Glad that you got it to work. There are plenty of hints about the correct PIN definitions and I will not provide support anymore. Hopefully you can get it from Jim in the future...
