### ISSUE TITLE
THX - BUT: **You are quite late to the show** and none of the cited code does have a .CONNECTED message. Both examples (receive and send) of the provided CAN-lib contain a message, when the CAN-Controller is not initialized by a false CS ("Error Initializing MCP2515..."). If you have a wiring problem with the OBD-cable there are also numerous details about the possible issues.

### ISSUE THREAD

**Issue by nighteagle1974** [MyLab-odyssey/ED_BMSdiag#35]
Oh--holy...S*
You are right - there it is - i have look at the wrong thing - dammned.
The best is to delete the complete issue - it was late yesterday.
But i have no problems all is working since yesterday evening and i change the Pin 2 to Pin8 thing liek keystudio CAN_Shield.

_Originally posted by @MyLab-odyssey in https://github.com/MyLab-odyssey/ED_BMSdiag/issues/33#issuecomment-1792281276_

**Comment by MyLab-odyssey** [comment]
😊 Happy that it is working now! And you are right about the INT pin. But the lib is from Cory Fowler and the CAN-shields in the past used pin 2 for INT. Glad you found it. Please post an issued with the solution for further users... THX
